
// Generated by https://quicktype.io


export interface Dishes {
    id:             string;
    nombre:         string;
    status:         string;
    categoria:      string;
  }

  export interface Dishes1 {
    id ?: number;
    nombrePlatillo?: string;
    categoriaID? : string;
    precio? : number
    esMenuDelDia? : boolean;
  }

