// Generated by https://quicktype.io

export interface Platillo {
    id: number;
    nombre: string;
    categoria: {
      id: number;
      nombre: string;
    };
    precio?: number; // Agregar propiedad precio opcional
  }
